#!/bin/bash

if ! command -v jq &> /dev/null; then
  echo "Requires jq (https://stedolan.github.io/jq)"
fi

transform='[.Lighting[] | {                                                                      ⇡ state-based-workaround :: ~5 … :: ⬡
  zone: .["Controller Zone"],
  button_name: .["Button Label"],
  address_1: .Address1,
  is_dimmer: (.Command == "DimmerSet")
}]'

if [[ $1 == *.plist ]]; then
  plutil -convert json -o - "$1" | jq -r "$transformation"
elif [[ $1 == *.json ]]; then
  jq -r "$transformation" "$1"
else
  echo "Invalid argument - expected plist or json file"
  exit 1
fi
